<?php

$words = array(
    'Seja bem vindo ao meu portifólio de projetos!',
    'Aqui você encontrará meus projetos e links para download.',
    'Aproveite e me siga nas redes sociais!',
    'Obrigado pela visita!',
    'Você é um visitante muito especial!',
    'Obrigado por estar aqui!',
    'Obrigado por me visitar!',
    'Obrigado por me acompanhar!',
    'Dá uma olhada nos meus projetos!',
    'Dá uma olhada nos meus links!',
    'Primeira vez aqui?',
    'Já conhece meus projetos?',
    'Sim eu sei, o texto muda toda vez que você atualiza a página.',
    'Como você está hoje?',
    'Como diria Michael Jackson, abiridin!',
    'Eu gosto de javascript, e você?',
    'Eu gosto de php, e você?',
    'Tenho um projeto em python, dá uma olhada!',
    'Será que eu foco em front-end ou back-end? Sei lá, os dois são legais.',
    'Eu gosto de programar, e você?',
    'Eu gosto de desenhar, e você?',
    'Eu gosto de jogar, e você?',
    'Tenho um amigo também programador, dá uma olhada no trabalho dele! @leandl no git!',
    'O verdadeiro tesouro é os amigos que fazemos no caminho.',
    'Sim eu faço apontamentos e referências aqui no header, deixa eu ser feliz ;-;',
    'Agradeço demais a todos que me ajudaram a chegar até aqui!',
    'Inclusive agradeço a você que está lendo isso agora!',
    'Infelizmente não tenho muito tempo para me dedicar a esse portifólio, mas sempre que posso dou uma atualizada.',
    'Infinito é o número de vezes que você pode atualizar essa página e ver um texto diferente. (Não é infinito, mas é bastante)',
    'Para sempre agradecido a meu colega de técnico Thiago, que me fez ter interesse em programação.',
    'Normalmente o que eu não gosto, eu acabo gostando, sim eu não gosto de kotlin e tenho um game em kotlin.',
    'Você é team front-end ou team back-end?',
    'Obrigado e volte sempre!',
    'Ryan, é você? (Se você é o Ryan, muito obrigado por me visitar! Senão, obrigado também!)',
    'Um dos meus sonhos é desenhar um quadrinho, mais já passei sufoco com isso, não é fácil.',
    'Tenho ideias, você quer escutar?',
    'As vezes eu me pergunto, quem está lendo isso?',
    'Sim, eu sei que você está lendo isso.',
    'Duvido você não ler isso.',
    'Duvido você saber o que é um oicanji.',
    'Meu nick Oicanji não é um animal, nem uma referência animal.',
    'Sim se você chutou que Oicanji é Ignacio com "J" no lugar do "G", você acertou.',
    'Me conte sobre você que eu te conto sobre mim.',
    'Já pensou em fazer um portifólio?',
    'Java.nullPointerException não é legal, mas é engraçado.',
    'This is the way.',
    'Não foi possível carregar o texto, tente novamente mais tarde. (Não é um erro, é só um texto aleatório mesmo)',
    '( ͡° ͜ʖ ͡°)',
    '(23:23:32 jul 23 2021) PHP ERROR: Undefined index: oicanji.php on line 1, cause: undefined variable $oicanji',
);

echo $words[rand(0, count($words) - 1)];
?>